### ISSUE TITLE
Windows 32/64 bit executables for Baislicka

### ISSUE THREAD

**Issue by ChessGUI** [kz04px/Baislicka-2.0#8]
Hello kz04px,

can you create Windows 32/64 bit executables of the source code please? My Ivy Bridge 22nm-structure computer supports AVX and POPCNT, but not BMI2 (=Haswell component). I write together with Ron Murawski (USA) contributions for the ComputerChess Wikipedia http://computer-chess.org/doku.php - all available WinBoard/XBoard and UCI compatibles chess engines are there mentioned.

Best wishes,

**Comment by kz04px** [comment]
I've made a release that includes 64 bit windows binaries and can be found here:
https://github.com/kz04px/Baislicka/releases/tag/v1.0

Feel free to report back with any issues you have.

Thanks
